

networks:
  gv-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  postgres :
    container_name: gestao_vagas_postgres
    image : postgres
    ports :
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=1234
     - POSTGRES_DB=gestao_vagas

  prometheus:
    container_name: gestao_vagas_prometheus
    image: prom/prometheus:latest
    volumes:
    - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus_data:/prometheus
    networks:
      - gv-network

    ports:
        - "9090:9090"

  grafana:
    container_name: gestao_vagas_grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - gv-network
    ports:
      - "3000:3000"